# Generated by Django 3.2.2 on 2021-08-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Level1',
            fields=[
                ('baselevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.baselevel')),
            ],
            options={
                'verbose_name': 'Уровень1',
                'verbose_name_plural': 'Уровень1',
            },
            bases=('myapp.baselevel',),
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('baselevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.baselevel')),
            ],
            options={
                'verbose_name': 'Уровень2',
                'verbose_name_plural': 'Уровень2',
            },
            bases=('myapp.baselevel',),
        ),
        migrations.CreateModel(
            name='Level3',
            fields=[
                ('baselevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.baselevel')),
            ],
            options={
                'verbose_name': 'Уровень3',
                'verbose_name_plural': 'Уровень3',
            },
            bases=('myapp.baselevel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('priceSP', models.IntegerField(verbose_name='Цена СП')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('properties', models.TextField(verbose_name='Поля свойств')),
                ('joint_purchases', models.TextField(verbose_name='Поля свойств')),
                ('picture', models.CharField(max_length=50, verbose_name='Код')),
                ('on_general', models.BooleanField(default=False, verbose_name='Выводить на главной')),
                ('note', models.TextField(verbose_name='Описание')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.unit')),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.level1')),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.level2')),
                ('level3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.level3')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
