# Generated by Django 3.2.2 on 2021-08-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='Наименование'),
        ),
    ]
