# Generated by Django 3.2.2 on 2021-08-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
